language: php

php:
  - 8.1
  - 8.2
  - 8.3
  - 8.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - composer test

matrix:
  fast_finish: true